export const COMPETITIONS = [
  {
    id: "uefa-champions-league",
    name: "UEFA Champions League",
    shortName: "UCL",
    type: "CLUB",
    country: "Europe",
    logo: "/images/competitions/ucl.png",
    tier: 1,
  },
  {
    id: "premier-league",
    name: "Premier League",
    shortName: "EPL",
    type: "LEAGUE",
    country: "England",
    logo: "/images/competitions/epl.png",
    tier: 1,
  },
  {
    id: "la-liga",
    name: "La Liga",
    shortName: "La Liga",
    type: "LEAGUE",
    country: "Spain",
    logo: "/images/competitions/laliga.png",
    tier: 1,
  },
  {
    id: "serie-a",
    name: "Serie A",
    shortName: "Serie A",
    type: "LEAGUE",
    country: "Italy",
    logo: "/images/competitions/seriea.png",
    tier: 1,
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    shortName: "Bundesliga",
    type: "LEAGUE",
    country: "Germany",
    logo: "/images/competitions/bundesliga.png",
    tier: 1,
  },
  {
    id: "ligue-1",
    name: "Ligue 1",
    shortName: "Ligue 1",
    type: "LEAGUE",
    country: "France",
    logo: "/images/competitions/ligue1.png",
    tier: 1,
  },
  {
    id: "caf-champions-league",
    name: "CAF Champions League",
    shortName: "CAF CL",
    type: "CLUB",
    country: "Africa",
    logo: "/images/competitions/cafcl.png",
    tier: 2,
  },
  {
    id: "botola-pro",
    name: "Botola Pro",
    shortName: "Botola",
    type: "LEAGUE",
    country: "Morocco",
    logo: "/images/competitions/botola.png",
    tier: 2,
  },
  {
    id: "fifa-world-cup",
    name: "FIFA World Cup",
    shortName: "World Cup",
    type: "INTERNATIONAL",
    country: "International",
    logo: "/images/competitions/worldcup.png",
    tier: 1,
  },
] as const;

export const MATCH_STATUSES = {
  SCHEDULED: "SCHEDULED",
  LIVE: "LIVE",
  HALF_TIME: "HALF_TIME",
  EXTRA_TIME: "EXTRA_TIME",
  PENALTIES: "PENALTIES",
  BREAK: "BREAK",
  FINISHED: "FINISHED",
  POSTPONED: "POSTPONED",
  CANCELLED: "CANCELLED",
  ABANDONED: "ABANDONED",
  SUSPENDED: "SUSPENDED",
  AWARDED: "AWARDED",
} as const;

export const EVENT_TYPES = {
  GOAL: "GOAL",
  ASSIST: "ASSIST",
  YELLOW_CARD: "YELLOW_CARD",
  RED_CARD: "RED_CARD",
  SECOND_YELLOW: "SECOND_YELLOW",
  SUBSTITUTION: "SUBSTITUTION",
  PENALTY_SCORED: "PENALTY_SCORED",
  PENALTY_MISSED: "PENALTY_MISSED",
  VAR: "VAR",
  OWN_GOAL: "OWN_GOAL",
  SAVE: "SAVE",
  INJURY: "INJURY",
  CORNER: "CORNER",
  FOUL: "FOUL",
  OFFSIDE: "OFFSIDE",
  SHOT_ON_TARGET: "SHOT_ON_TARGET",
  SHOT_OFF_TARGET: "SHOT_OFF_TARGET",
  WOODWORK: "WOODWORK",
} as const;

export const POSITIONS = {
  GK: { code: "GK", name: "Goalkeeper", category: "GOALKEEPER" },
  CB: { code: "CB", name: "Center Back", category: "DEFENDER" },
  LB: { code: "LB", name: "Left Back", category: "DEFENDER" },
  RB: { code: "RB", name: "Right Back", category: "DEFENDER" },
  LWB: { code: "LWB", name: "Left Wing Back", category: "DEFENDER" },
  RWB: { code: "RWB", name: "Right Wing Back", category: "DEFENDER" },
  CDM: { code: "CDM", name: "Central Defensive Midfielder", category: "MIDFIELDER" },
  CM: { code: "CM", name: "Central Midfielder", category: "MIDFIELDER" },
  LM: { code: "LM", name: "Left Midfielder", category: "MIDFIELDER" },
  RM: { code: "RM", name: "Right Midfielder", category: "MIDFIELDER" },
  CAM: { code: "CAM", name: "Central Attacking Midfielder", category: "MIDFIELDER" },
  LW: { code: "LW", name: "Left Winger", category: "FORWARD" },
  RW: { code: "RW", name: "Right Winger", category: "FORWARD" },
  CF: { code: "CF", name: "Center Forward", category: "FORWARD" },
  ST: { code: "ST", name: "Striker", category: "FORWARD" },
} as const;

export const ROLES = {
  GUEST: "GUEST",
  USER: "USER",
  ADMIN: "ADMIN",
} as const;

export const NOTIFICATION_TYPES = {
  MATCH_START: "MATCH_START",
  MATCH_GOAL: "MATCH_GOAL",
  MATCH_END: "MATCH_END",
  MATCH_REMINDER: "MATCH_REMINDER",
  SUBSCRIPTION: "SUBSCRIPTION",
  SYSTEM: "SYSTEM",
  FANTASY: "FANTASY",
  NEWS: "NEWS",
  TRANSFER: "TRANSFER",
} as const;

export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", flag: "/images/flags/af.png" },
  { code: "AL", name: "Albania", flag: "/images/flags/al.png" },
  { code: "DZ", name: "Algeria", flag: "/images/flags/dz.png" },
  { code: "AR", name: "Argentina", flag: "/images/flags/ar.png" },
  { code: "AM", name: "Armenia", flag: "/images/flags/am.png" },
  { code: "AU", name: "Australia", flag: "/images/flags/au.png" },
  { code: "AT", name: "Austria", flag: "/images/flags/at.png" },
  { code: "AZ", name: "Azerbaijan", flag: "/images/flags/az.png" },
  { code: "BH", name: "Bahrain", flag: "/images/flags/bh.png" },
  { code: "BD", name: "Bangladesh", flag: "/images/flags/bd.png" },
  { code: "BY", name: "Belarus", flag: "/images/flags/by.png" },
  { code: "BE", name: "Belgium", flag: "/images/flags/be.png" },
  { code: "BJ", name: "Benin", flag: "/images/flags/bj.png" },
  { code: "BO", name: "Bolivia", flag: "/images/flags/bo.png" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "/images/flags/ba.png" },
  { code: "BR", name: "Brazil", flag: "/images/flags/br.png" },
  { code: "BG", name: "Bulgaria", flag: "/images/flags/bg.png" },
  { code: "BF", name: "Burkina Faso", flag: "/images/flags/bf.png" },
  { code: "CM", name: "Cameroon", flag: "/images/flags/cm.png" },
  { code: "CA", name: "Canada", flag: "/images/flags/ca.png" },
  { code: "CF", name: "Central African Republic", flag: "/images/flags/cf.png" },
  { code: "TD", name: "Chad", flag: "/images/flags/td.png" },
  { code: "CL", name: "Chile", flag: "/images/flags/cl.png" },
  { code: "CN", name: "China", flag: "/images/flags/cn.png" },
  { code: "CO", name: "Colombia", flag: "/images/flags/co.png" },
  { code: "CD", name: "Congo DR", flag: "/images/flags/cd.png" },
  { code: "CG", name: "Congo", flag: "/images/flags/cg.png" },
  { code: "CR", name: "Costa Rica", flag: "/images/flags/cr.png" },
  { code: "CI", name: "Côte d'Ivoire", flag: "/images/flags/ci.png" },
  { code: "HR", name: "Croatia", flag: "/images/flags/hr.png" },
  { code: "CU", name: "Cuba", flag: "/images/flags/cu.png" },
  { code: "CY", name: "Cyprus", flag: "/images/flags/cy.png" },
  { code: "CZ", name: "Czech Republic", flag: "/images/flags/cz.png" },
  { code: "DK", name: "Denmark", flag: "/images/flags/dk.png" },
  { code: "DO", name: "Dominican Republic", flag: "/images/flags/do.png" },
  { code: "EC", name: "Ecuador", flag: "/images/flags/ec.png" },
  { code: "EG", name: "Egypt", flag: "/images/flags/eg.png" },
  { code: "SV", name: "El Salvador", flag: "/images/flags/sv.png" },
  { code: "GQ", name: "Equatorial Guinea", flag: "/images/flags/gq.png" },
  { code: "ER", name: "Eritrea", flag: "/images/flags/er.png" },
  { code: "EE", name: "Estonia", flag: "/images/flags/ee.png" },
  { code: "ET", name: "Ethiopia", flag: "/images/flags/et.png" },
  { code: "FI", name: "Finland", flag: "/images/flags/fi.png" },
  { code: "FR", name: "France", flag: "/images/flags/fr.png" },
  { code: "GA", name: "Gabon", flag: "/images/flags/ga.png" },
  { code: "GM", name: "Gambia", flag: "/images/flags/gm.png" },
  { code: "GE", name: "Georgia", flag: "/images/flags/ge.png" },
  { code: "DE", name: "Germany", flag: "/images/flags/de.png" },
  { code: "GH", name: "Ghana", flag: "/images/flags/gh.png" },
  { code: "GR", name: "Greece", flag: "/images/flags/gr.png" },
  { code: "GT", name: "Guatemala", flag: "/images/flags/gt.png" },
  { code: "GN", name: "Guinea", flag: "/images/flags/gn.png" },
  { code: "GW", name: "Guinea-Bissau", flag: "/images/flags/gw.png" },
  { code: "HT", name: "Haiti", flag: "/images/flags/ht.png" },
  { code: "HN", name: "Honduras", flag: "/images/flags/hn.png" },
  { code: "HK", name: "Hong Kong", flag: "/images/flags/hk.png" },
  { code: "HU", name: "Hungary", flag: "/images/flags/hu.png" },
  { code: "IS", name: "Iceland", flag: "/images/flags/is.png" },
  { code: "IN", name: "India", flag: "/images/flags/in.png" },
  { code: "ID", name: "Indonesia", flag: "/images/flags/id.png" },
  { code: "IR", name: "Iran", flag: "/images/flags/ir.png" },
  { code: "IQ", name: "Iraq", flag: "/images/flags/iq.png" },
  { code: "IE", name: "Ireland", flag: "/images/flags/ie.png" },
  { code: "IL", name: "Israel", flag: "/images/flags/il.png" },
  { code: "IT", name: "Italy", flag: "/images/flags/it.png" },
  { code: "JM", name: "Jamaica", flag: "/images/flags/jm.png" },
  { code: "JP", name: "Japan", flag: "/images/flags/jp.png" },
  { code: "JO", name: "Jordan", flag: "/images/flags/jo.png" },
  { code: "KZ", name: "Kazakhstan", flag: "/images/flags/kz.png" },
  { code: "KE", name: "Kenya", flag: "/images/flags/ke.png" },
  { code: "KW", name: "Kuwait", flag: "/images/flags/kw.png" },
  { code: "KG", name: "Kyrgyzstan", flag: "/images/flags/kg.png" },
  { code: "LA", name: "Laos", flag: "/images/flags/la.png" },
  { code: "LV", name: "Latvia", flag: "/images/flags/lv.png" },
  { code: "LB", name: "Lebanon", flag: "/images/flags/lb.png" },
  { code: "LR", name: "Liberia", flag: "/images/flags/lr.png" },
  { code: "LY", name: "Libya", flag: "/images/flags/ly.png" },
  { code: "LI", name: "Liechtenstein", flag: "/images/flags/li.png" },
  { code: "LT", name: "Lithuania", flag: "/images/flags/lt.png" },
  { code: "LU", name: "Luxembourg", flag: "/images/flags/lu.png" },
  { code: "MG", name: "Madagascar", flag: "/images/flags/mg.png" },
  { code: "MW", name: "Malawi", flag: "/images/flags/mw.png" },
  { code: "MY", name: "Malaysia", flag: "/images/flags/my.png" },
  { code: "ML", name: "Mali", flag: "/images/flags/ml.png" },
  { code: "MT", name: "Malta", flag: "/images/flags/mt.png" },
  { code: "MR", name: "Mauritania", flag: "/images/flags/mr.png" },
  { code: "MU", name: "Mauritius", flag: "/images/flags/mu.png" },
  { code: "MX", name: "Mexico", flag: "/images/flags/mx.png" },
  { code: "MD", name: "Moldova", flag: "/images/flags/md.png" },
  { code: "MC", name: "Monaco", flag: "/images/flags/mc.png" },
  { code: "MN", name: "Mongolia", flag: "/images/flags/mn.png" },
  { code: "ME", name: "Montenegro", flag: "/images/flags/me.png" },
  { code: "MA", name: "Morocco", flag: "/images/flags/ma.png" },
  { code: "MZ", name: "Mozambique", flag: "/images/flags/mz.png" },
  { code: "MM", name: "Myanmar", flag: "/images/flags/mm.png" },
  { code: "NA", name: "Namibia", flag: "/images/flags/na.png" },
  { code: "NP", name: "Nepal", flag: "/images/flags/np.png" },
  { code: "NL", name: "Netherlands", flag: "/images/flags/nl.png" },
  { code: "NZ", name: "New Zealand", flag: "/images/flags/nz.png" },
  { code: "NI", name: "Nicaragua", flag: "/images/flags/ni.png" },
  { code: "NE", name: "Niger", flag: "/images/flags/ne.png" },
  { code: "NG", name: "Nigeria", flag: "/images/flags/ng.png" },
  { code: "KP", name: "North Korea", flag: "/images/flags/kp.png" },
  { code: "MK", name: "North Macedonia", flag: "/images/flags/mk.png" },
  { code: "NO", name: "Norway", flag: "/images/flags/no.png" },
  { code: "OM", name: "Oman", flag: "/images/flags/om.png" },
  { code: "PK", name: "Pakistan", flag: "/images/flags/pk.png" },
  { code: "PS", name: "Palestine", flag: "/images/flags/ps.png" },
  { code: "PA", name: "Panama", flag: "/images/flags/pa.png" },
  { code: "PY", name: "Paraguay", flag: "/images/flags/py.png" },
  { code: "PE", name: "Peru", flag: "/images/flags/pe.png" },
  { code: "PH", name: "Philippines", flag: "/images/flags/ph.png" },
  { code: "PL", name: "Poland", flag: "/images/flags/pl.png" },
  { code: "PT", name: "Portugal", flag: "/images/flags/pt.png" },
  { code: "QA", name: "Qatar", flag: "/images/flags/qa.png" },
  { code: "RO", name: "Romania", flag: "/images/flags/ro.png" },
  { code: "RU", name: "Russia", flag: "/images/flags/ru.png" },
  { code: "RW", name: "Rwanda", flag: "/images/flags/rw.png" },
  { code: "SA", name: "Saudi Arabia", flag: "/images/flags/sa.png" },
  { code: "SN", name: "Senegal", flag: "/images/flags/sn.png" },
  { code: "RS", name: "Serbia", flag: "/images/flags/rs.png" },
  { code: "SL", name: "Sierra Leone", flag: "/images/flags/sl.png" },
  { code: "SG", name: "Singapore", flag: "/images/flags/sg.png" },
  { code: "SK", name: "Slovakia", flag: "/images/flags/sk.png" },
  { code: "SI", name: "Slovenia", flag: "/images/flags/si.png" },
  { code: "SO", name: "Somalia", flag: "/images/flags/so.png" },
  { code: "ZA", name: "South Africa", flag: "/images/flags/za.png" },
  { code: "KR", name: "South Korea", flag: "/images/flags/kr.png" },
  { code: "SS", name: "South Sudan", flag: "/images/flags/ss.png" },
  { code: "ES", name: "Spain", flag: "/images/flags/es.png" },
  { code: "LK", name: "Sri Lanka", flag: "/images/flags/lk.png" },
  { code: "SD", name: "Sudan", flag: "/images/flags/sd.png" },
  { code: "SR", name: "Suriname", flag: "/images/flags/sr.png" },
  { code: "SE", name: "Sweden", flag: "/images/flags/se.png" },
  { code: "CH", name: "Switzerland", flag: "/images/flags/ch.png" },
  { code: "SY", name: "Syria", flag: "/images/flags/sy.png" },
  { code: "TW", name: "Taiwan", flag: "/images/flags/tw.png" },
  { code: "TJ", name: "Tajikistan", flag: "/images/flags/tj.png" },
  { code: "TZ", name: "Tanzania", flag: "/images/flags/tz.png" },
  { code: "TH", name: "Thailand", flag: "/images/flags/th.png" },
  { code: "TL", name: "Timor-Leste", flag: "/images/flags/tl.png" },
  { code: "TG", name: "Togo", flag: "/images/flags/tg.png" },
  { code: "TT", name: "Trinidad and Tobago", flag: "/images/flags/tt.png" },
  { code: "TN", name: "Tunisia", flag: "/images/flags/tn.png" },
  { code: "TR", name: "Turkey", flag: "/images/flags/tr.png" },
  { code: "TM", name: "Turkmenistan", flag: "/images/flags/tm.png" },
  { code: "UG", name: "Uganda", flag: "/images/flags/ug.png" },
  { code: "UA", name: "Ukraine", flag: "/images/flags/ua.png" },
  { code: "AE", name: "United Arab Emirates", flag: "/images/flags/ae.png" },
  { code: "GB", name: "United Kingdom", flag: "/images/flags/gb.png" },
  { code: "US", name: "United States", flag: "/images/flags/us.png" },
  { code: "UY", name: "Uruguay", flag: "/images/flags/uy.png" },
  { code: "UZ", name: "Uzbekistan", flag: "/images/flags/uz.png" },
  { code: "VE", name: "Venezuela", flag: "/images/flags/ve.png" },
  { code: "VN", name: "Vietnam", flag: "/images/flags/vn.png" },
  { code: "YE", name: "Yemen", flag: "/images/flags/ye.png" },
  { code: "ZM", name: "Zambia", flag: "/images/flags/zm.png" },
  { code: "ZW", name: "Zimbabwe", flag: "/images/flags/zw.png" },
] as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const;

export const CACHE_KEYS = {
  LIVE_MATCHES: "live_matches",
  MATCH_DETAIL: (id: string) => `match:${id}`,
  STANDINGS: (competitionId: string) => `standings:${competitionId}`,
  TOP_SCORERS: (competitionId: string) => `top_scorers:${competitionId}`,
  USER_PREFERENCES: (userId: string) => `user:${userId}:preferences`,
  COMPETITIONS: "competitions",
  TEAMS: "teams",
  NEWS: "news",
} as const;

export type CompetitionId = (typeof COMPETITIONS)[number]["id"];
export type MatchStatus = keyof typeof MATCH_STATUSES;
export type EventType = keyof typeof EVENT_TYPES;
export type PositionCode = keyof typeof POSITIONS;
export type Role = keyof typeof ROLES;
export type NotificationType = keyof typeof NOTIFICATION_TYPES;
export type CountryCode = (typeof COUNTRIES)[number]["code"];
